apiVersion: v1
kind: Service
metadata:
  name: nginx-hello
spec:
  selector:
    app: nginx-hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-hello
  spec:
    replicas: 1
    selector:
      matchLabels: 
        app: nginx-hello 
    template:
      metadata:
        labels:
          app: nginx-hello
      spec:
        containers:
        - name: nginx-hello
          image: flippyboy/nginx-hello
          ports:
          - containerPort: 80